data:
  batch_size: 64
  test_batch_size: 1000
  noise_factor: 0.9

model:
  input_size: 784
  hidden_size: 256
  num_classes: 10
  beta: 1.0
  sparsity_threshold: -0.1

training:
  epochs: 15
  learning_rate: 0.001
  log_interval: 100

device: "cuda"
